// CLEAR
export const CLEAR_TAGS = 'CLEAR_TAGS';
export const CLEAR_CODINGLANGS = 'CLEAR_CODINGLANGS';
export const CLEAR_MADEATS = 'CLEAR_MADEATS';

//FETCH PROJECTS
export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

//FETCH TAGS
export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';

//FETCH CODINGLANGS
export const FETCH_CODINGLANGS_REQUEST = 'FETCH_CODINGLANGS_REQUEST';
export const FETCH_CODINGLANGS_SUCCESS = 'FETCH_CODINGLANGS_SUCCESS';
export const FETCH_CODINGLANGS_FAILURE = 'FETCH_CODINGLANGS_FAILURE';

//FETCH MADEATS
export const FETCH_MADEATS_REQUEST = 'FETCH_MADEATS_REQUEST';
export const FETCH_MADEATS_SUCCESS = 'FETCH_MADEATS_SUCCESS';
export const FETCH_MADEATS_FAILURE = 'FETCH_MADEATS_FAILURE';

//FETCH CONTACT FORMS
export const FETCH_CONTACTFORMS_REQUEST = 'FETCH_CONTACTFORMS_REQUEST';
export const FETCH_CONTACTFORMS_SUCCESS = 'FETCH_CONTACTFORMS_SUCCESS';
export const FETCH_CONTACTFORMS_FAILURE = 'FETCH_CONTACTFORMS_FAILURE';

//FETCH USERS
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//LOGOUT
export const LOGOUT = 'LOGOUT';
