// CLEAR
export const CLEAR_TAGS = 'CLEAR_TAGS';
export const CLEAR_CODINGLANGS = 'CLEAR_CODINGLANGS';
export const CLEAR_MADEATS = 'CLEAR_MADEATS';

//FETCH PROJECTS
export const FETCH_PROJECTS_BEGIN = 'FETCH_PROJECTS_BEGIN';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

//FETCH TAGS
export const FETCH_TAGS_BEGIN = 'FETCH_TAGS_BEGIN';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';

//FETCH CODINGLANGS
export const FETCH_CODINGLANGS_BEGIN = 'FETCH_CODINGLANGS_BEGIN';
export const FETCH_CODINGLANGS_SUCCESS = 'FETCH_CODINGLANGS_SUCCESS';
export const FETCH_CODINGLANGS_FAILURE = 'FETCH_CODINGLANGS_FAILURE';

//FETCH MADEATS
export const FETCH_MADEATS_BEGIN = 'FETCH_MADEATS_BEGIN';
export const FETCH_MADEATS_SUCCESS = 'FETCH_MADEATS_SUCCESS';
export const FETCH_MADEATS_FAILURE = 'FETCH_MADEATS_FAILURE';

//FETCH CONTACT FORMS
export const FETCH_CONTACTFORMS_BEGIN = 'FETCH_CONTACTFORMS_BEGIN';
export const FETCH_CONTACTFORMS_SUCCESS = 'FETCH_CONTACTFORMS_SUCCESS';
export const FETCH_CONTACTFORMS_FAILURE = 'FETCH_CONTACTFORMS_FAILURE';
